services:
  web:
    image: php:8.2-apache
    container_name: web-J-J-Proyect
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    command: /bin/sh -c "docker-php-ext-install mysqli pdo pdo_mysql && a2enmod rewrite && apache2-foreground"

  db:
    image: mariadb:11
    container_name: db-J-J-Proyect
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=JJPROYECT
      - MARIADB_USER=app
      - MARIADB_PASSWORD=app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:5
    container_name: pma-J-J-Proyect
    restart: unless-stopped
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    ports:
      - "8081:80"

volumes:
  db_data: {}